version: '3.8'
services:
  web:
    build:
      context: .  # Контекст вказує на кореневу папку
      dockerfile: Dockerfile
    volumes:
      - ./exchanger:/app/exchanger  # Синхронізуємо локальну папку `exchanger` з папкою в контейнері
    ports:
      - "80:80"  # Перенаправляємо порт 80 на локальний порт 80
